openapi: 3.0.3
info:
  title: Table Prediction API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /table-prediction:
    get:
      summary: "Zwraca listę predykcji tabeli ligowej"
      responses:
        '200':
          description: "Lista predykcji"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TablePredictionModel'

  /team-strength:
    get:
      summary: "Zwraca siłę drużyn (footballClubCode -> strength)"
      responses:
        '200':
          description: "Mapa siły drużyn"
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: number
                  format: double

components:
  schemas:
    TablePredictionModel:
      type: object
      properties:
        id:
          type: string
        footballClubCode:
          type: string
        timestamp:
          type: string
          format: date-time
        matchPlayed:
          type: integer
          format: int32
        ranking:
          type: integer
          format: int32
        points:
          type: integer
          format: int32
        top4Prediction:
          type: number
          format: double
        relegationPrediction:
          type: number
          format: double
      required:
        - footballClubCode
        - timestamp
        - ranking
        - points
