openapi: 3.0.3
info:
  title: Table Prediction API
  version: 1.0.0
paths:
  /table-prediction:
    get:
      summary: "Zwraca przewidywaną tabelę ligi na podstawie dostępnych wyników"
      parameters:
        - name: simulationIterations
          in: query
          description: "Liczba iteracji symulacji (opcjonalne, domyślnie 2000)"
          required: false
          schema:
            type: integer
            format: int32
            default: 2000
      responses:
        '200':
          description: "Tabela ligowa (predykcja)"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueTableModel'
        '400':
          description: "Błędny parametr wejściowy"
components:
  schemas:
    FootballClubModel:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
        code:
          type: string
      required:
        - name
        - code
    LeagueStandingsEntryModel:
      type: object
      properties:
        footballClub:
          $ref: '#/components/schemas/FootballClubModel'
        position:
          type: integer
        playedGames:
          type: integer
        wonGames:
          type: integer
        drawnGames:
          type: integer
        lostGames:
          type: integer
        goalsFor:
          type: integer
        goalsAgainst:
          type: integer
        goalDifference:
          type: integer
        points:
          type: integer
      required:
        - footballClub
        - position
        - points
    LeagueTableModel:
      type: object
      properties:
        standingsEntry:
          type: array
          items:
            $ref: '#/components/schemas/LeagueStandingsEntryModel'
      required:
        - standingsEntry

